### ISSUE TITLE
`vscode-html-language-server` etc. are incorrectly configured by default

### ISSUE THREAD

**Issue by nonk123** [kakoune-lsp/kakoune-lsp#731]
I installed `vscode-html-language-server` and its relatives with `npm i -g vscode-langservers-extracted` and was unable to get it running out of the box due to this section in `kak-lsp.toml`:

```toml
[language_server.html-language-server]
filetypes = ["html"]
roots = ["package.json"]
command = "vscode-html-languageserver"
args = ["--stdio"]
```

Shouldn't it have this instead?

```toml
command = "vscode-html-language-server"
```

The same applies to the rest of the `vscode-*-language-server`s.
