### ISSUE TITLE
gopls inlay hints

### ISSUE THREAD

**Issue by mlhhqh** [kakoune-lsp/kakoune-lsp#734]
I am using kakoune with kak-lsp and inlay hints do work under rust (rust-analyzer).
Using gopls though I get no inlay hints (even after explicitly enabling them multiple times).
Looking at the debug buffer I see no inlayHints requests anywhere for gopls.

On Emacs you need to set this additional config:
```
(add-to-list 'eglot-server-programs '((go-mode go-ts-mode) .
    ("gopls" :initializationOptions
      (:hints (:parameterNames t
               :rangeVariableTypes t
               :functionTypeParameters t
               :assignVariableTypes t
               :compositeLiteralFields t
               :compositeLiteralTypes t
               :constantValues t)))))
```

So maybe there is additional config required for gopls?

**Comment by krobelus** [comment]
right, they need to be turned on as described [here](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#navigation)

A working config is

```toml
[language_server.gopls]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "gopls"
[language_server.gopls.settings.gopls]
# See https://github.com/golang/tools/blob/master/gopls/doc/settings.md
# "build.buildFlags" = []
hints.assignVariableTypes = true
hints.compositeLiteralFields = true
hints.compositeLiteralTypes = true
hints.constantValues = true
hints.functionTypeParameters = true
hints.parameterNames = true
hints.rangeVariableTypes = true
"ui.completion.usePlaceholders" = true
```

which I just made the default. Thanks for reporting!
