### ISSUE TITLE
Add Biome to example config

### ISSUE THREAD

**Issue by notramo** [kakoune-lsp/kakoune-lsp#750]
Biome is a fast, all-in-one toolchain for web projects (JS, TS, CSS, HTML), written in Rust.
https://biomejs.dev/guides/integrate-in-editor/

**Comment by krobelus** [comment]
sure that would be welcome (commented in kak-lsp.toml, unless we make it the default).
You can directly translate the neovim config, LMK if you need help

**Comment by notramo** [comment]
@krobelus it works for me using this config:
```toml
[language_server.biome]
filetypes = ["typescript", "javascript"]
roots = ["biome.json", "package.json", "tsconfig.json", "jsconfig.json", ".git", ".hg"]
command = "biome"
args = ["lsp-proxy"]
```
