### ISSUE TITLE
Add `zk` to example config

### ISSUE THREAD

**Issue by notramo** [kakoune-lsp/kakoune-lsp#751]
`zk` is a CLI tool for managing Zettelkasten notes.
It should be configured to `markdown` filetype.
It has a `.zk` directory in the project root.
https://github.com/zk-org/zk/blob/main/docs/editors-integration.md

**Comment by notramo** [comment]
Here is a code snippet that works for me.
```toml
[language_server.zk]
filetypes = ["markdown"]
roots = [".zk"]
command = "zk"
args = ["lsp"]
```
