### ISSUE TITLE
Add Svelte to example config

### ISSUE THREAD

**Issue by notramo** [kakoune-lsp/kakoune-lsp#752]
https://github.com/sveltejs/language-tools

This snippet works for me, feel free to use it:
```toml
[language_server.svelte-language-server]
filetypes = ["svelte"]
roots = ["package.json", "tsconfig.json", "jsconfig.json", ".git", ".hg"]
command = "svelteserver"
args = ["--stdio"]
```
