### ISSUE TITLE
Add htmx support 

### ISSUE THREAD

**Issue by Yappaholic** [kakoune-lsp/kakoune-lsp#760]
There are quite a bit of htmx language servers, but one that gets to work good in helix and at least can be configured in kakoune is [htmx-lsp2](https://github.com/uros-5/htmx-lsp2).

Right now I can get to initialize step, with this kak-lsp log:
```kak
LSP: log from htmx: initialized!

```
With this config in `kak-lsp.toml`:
```toml
[language_server.htmx]
filetypes = ["templ"]
command = "/home/savvy/.cargo/bin/htmx-lsp2"
roots = ["index.templ"]
settings_section = "config"

[language_server.htmx.settings.config]
"lang" = "go"
"template_ext" = "templ"
"templates" = ["../views", "views", "./views"]
"backend_tags" = []
"js_tags" = []

```
Config in helix looks like this: 
```toml
[language-server.htmx-lsp]
command = "/home/savvy/.cargo/bin/htmx-lsp2"
config = { lang = "go", template_ext = "templ", templates = ["views", "./views"], backend_tags = [], js_tags = [] }
timeout = 5

```
Still, even with proper init there is no autocompletion, so it would be nice to add some type of official support for htmx.

**Comment by krobelus** [comment]
I can't get it to work in helix, can you give a (minimal) example project where it works? I'm running with

```toml
[language-server.htmx-lsp]
command = "htmx-lsp2"
config = { lang = "go", template_ext = "templ", templates = ["views", "./views"], backend_tags = [], js_tags = [] }
timeout = 5
[[language]]
name = "html"
language-servers = ["htmx-lsp"]
```

**Comment by Yappaholic** [comment]
> I can't get it to work in helix, can you give a (minimal) example project where it works? I'm running with
> 
> ```toml
> [language-server.htmx-lsp]
> command = "htmx-lsp2"
> config = { lang = "go", template_ext = "templ", templates = ["views", "./views"], backend_tags = [], js_tags = [] }
> timeout = 5
> [[language]]
> name = "html"
> language-servers = ["htmx-lsp"]
> ```

Right now there's only support for backend languages(Rust, Go), but it can be changed in the future.
For project to try LSP you can clone my [Golang repo](https://github.com/Yappaholic/pokemon-htmx)

There is also more popular LSP by Primeagen called [htmx-lsp](https://github.com/ThePrimeagen/htmx-lsp), but it doesn't seem to work neither in helix nor in kakoune, and it gets other LSPs to not load.

**Comment by krobelus** [comment]
Thanks, I got both HTML tag and Go code completions to work in Helix.
I noticed that it only works if `templ` is installed.
And configured (I guess there is a default config somewhere in helix).
I added this in addition to the htmx

```toml
[language_server.templ]
filetypes = ["templ"]
command = "templ"
roots = [".git", ".hg"]
args = ["lsp"]
```


Unfortunately, `templ` crashes when facing kakoune-lsp. Reported as https://github.com/a-h/templ/issues/873

**Comment by krobelus** [comment]
Ok I got templ to work. I get Go completions now.

But no HTML tag completions from htmx-lsp2 (which works in Helix).
I verified that both Helix and kakoune-lsp send the same `workspace/didChangeConfiguration`.
Opening an upstream issue I guess.

**Comment by krobelus** [comment]
reported as https://github.com/uros-5/htmx-lsp2/issues/4

**Comment by Yappaholic** [comment]
> reported as [uros-5/htmx-lsp2#4](https://github.com/uros-5/htmx-lsp2/issues/4)

Thanks.
Also, I got Primeagen's [htmx-lsp](https://github.com/ThePrimeagen/htmx-lsp) to work with `.html` files in Helix with this config:
```toml
[language-server.htmx-lsp]
command = "htmx-lsp"
```
But when exiting file it freezes and prints to stderr(?) `Error: Timed out waiting for language servers to shutdown`
