### ISSUE TITLE
`bash-language-server` crashes with `unwrap()` on `None`

### ISSUE THREAD

**Issue by clarfonthey** [kakoune-lsp/kakoune-lsp#830]
I am using the recommended settings for this LSP:

```toml
[language.bash]
filetypes = ["sh"]
roots = [".git"]
command = "bash-language-server"
args = ["start"]
```

And running on 18.1.2. It appears that the only useful error here is:

```
LSP: ERRO kak-lsp crashed; disabling hooks for this buffer.
Please report an issue or send this crash report.
See the *debug* buffer for more info.

panicked at src/controller.rs:1455:67:
called `Option::unwrap()` on a `None` value
disabled backtrace
```

(this happens any time this server is used, and it mostly just dumps this error, the contents of the editor, and the relevant LSP config section to `*debug*`)

I updated after accidentally going a while without updating, so, the best I can give you is that this worked in 14.2.0 for me and is now failing on 18.1.2. I can provide more details as needed, although I'm just assuming that this is a case in the code that was missed for the moment.
